### PR TITLE
add test for commandline

### PR DESCRIPTION
**Pull request by WangGithub0**
write test for src/utils/commandline.py file, coverage from 70%->84%
image

closes https://github.com/Amnish04/til-page-builder/issues/27

### CODE REVIEW

**Comment by Amnish04** [comment]
Hi Yumei, the logic for your unit test looks good. But it is not being collected or run by pytest since its not part of a function/method.

You'll need to add it to a method instead of directly putting in the class like so.
image

Also, could you please make a separate file for this class, since the pattern is to have a `test` file for every `source` file.
In your case, it would be `tests/utils/test_commandline.py`.
And the root class name would be `TestCommandline`. You can put all your test logic in a method for this class.

**Comment by Amnish04** [comment]
> Hi Yumei, the logic for your unit test looks good. But it is not being collected or run by pytest since its not part of a function/method.
> 
> You'll need to add it to a method instead of directly putting in the class like so. image
> 
> Also, could you please make a separate file for this class, since the pattern is to have a `test` file for every `source` file. In your case, it would be `tests/utils/test_commandline.py`. And the root class name would be `TestCommandline`. You can put all your test logic in a method for this class.
> 
> Lastly, I just noticed that the integration test is failing when running from a pull request. This should be from my side, will check now

Just found that the integration test is being interupted by the class

> Hi Yumei, the logic for your unit test looks good. But it is not being collected or run by pytest since its not part of a function/method.
> 
> You'll need to add it to a method instead of directly putting in the class like so. image
> 
> Also, could you please make a separate file for this class, since the pattern is to have a `test` file for every `source` file. In your case, it would be `tests/utils/test_commandline.py`. And the root class name would be `TestCommandline`. You can put all your test logic in a method for this class.
> 
> Lastly, I just noticed that the integration test is failing when running from a pull request. This should be from my side, will check now

Just found that the integration test is being interupted by the commandline test you added. It runs fine without it, we need to find out why.

**Review by Amnish04 — CHANGES_REQUESTED** [review]
Hi Yumei, the logic for your unit test looks good. But it is not being collected or run by pytest since its not part of a function/method.

You'll need to add it to a method instead of directly putting in the class like so.
image

Also, could you please make a separate file for this class, since the pattern is to have a `test` file for every `source` file.
In your case, it would be `tests/utils/test_commandline.py`.
And the root class name would be `TestCommandline`. You can put all your test logic in a method for this class.

**Comment by WangGithub0** [comment]
hi @Amnish04, thanks for your comments, I've already revise my code, help me view please.

**Comment by Amnish04** [comment]
> hi @Amnish04, thanks for your comments, I've already revise my code, help me view please.

@WangGithub0 Thanks for the changes.
 I see that there are a couple of **lint errors** with your imports which is failing the CI.
image

Fixing those should run the tests step.

**Comment by Amnish04** [comment]
@WangGithub0 Hi Yumei, I think the change to the `sys.argv` in your test for commandline arguments is being carried on to other tests as well, hence interfering with the `integration test` run.

I would suggest storing the original state of that system variable before patching it, and then restore that state once you're done with your tests like this.

```python
# Save the original sys.argv
original_argv = sys.argv.copy()

# Apply the patch to sys.argv to mimic command-line arguments
with patch.object(sys, "argv", ["commandline.py"] + arguments):
    # Create an instance of the CommandlineParser
    parser = CommandlineParser()

    # Get the parsed arguments
    args = parser.get_args()

    # Assert that the arguments are correctly parsed
    assert args.config == "config.toml"
    assert args.input_path == "input.md"
    assert args.output == "./dist/til"
    assert args.version

# After the block, revert sys.argv to its original state
sys.argv = original_argv
```

**Comment by Amnish04** [comment]
@WangGithub0 
Found the problem!

My implementation of CommandlineParser was to only have one instance of the class in a single run.
image

which is why the new arguments are never parsed and loaded
image

Changing that to normal `__init__` fixes the issue.
image

**Comment by Amnish04** [comment]
@WangGithub0 Just pushed the fix.
https://github.com/Amnish04/til-page-builder/commit/fbd02234430d316890dd1d488f61bbcf729d30df

You can pull latest from [master](https://github.com/Amnish04/til-page-builder/tree/master)

**Comment by WangGithub0** [comment]
> @WangGithub0 Just pushed the fix [fbd0223](https://github.com/Amnish04/til-page-builder/commit/fbd02234430d316890dd1d488f61bbcf729d30df)
> 
> You can pull latest from [master](https://github.com/Amnish04/til-page-builder/tree/master)

will the test run again automatically?

**Comment by Amnish04** [comment]
> > @WangGithub0 Just pushed the fix [fbd0223](https://github.com/Amnish04/til-page-builder/commit/fbd02234430d316890dd1d488f61bbcf729d30df)
> > You can pull latest from [master](https://github.com/Amnish04/til-page-builder/tree/master)
> 
> will the test run again automatically?

Yes

**Comment by Amnish04** [comment]
> > @WangGithub0 Just pushed the fix [fbd0223](https://github.com/Amnish04/til-page-builder/commit/fbd02234430d316890dd1d488f61bbcf729d30df)
> > You can pull latest from [master](https://github.com/Amnish04/til-page-builder/tree/master)
> 
> will the test run again automatically?

@WangGithub0 
You'll have to pull the latest from `upstream master` and push to your branch on `origin`.

**Comment by Amnish04** [comment]
@WangGithub0 Thanks for the contribution!

**Pull request merged**
